/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VENTANAS;

import EDD.Tree;
import Extras.Funciones;
import JSON.LecturaJSON;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.graphstream.graph.implementations.MultiGraph;

/**
 *
 * @author marco
 */
public class CONTROL_REGISTROS extends javax.swing.JFrame {
    static LecturaJSON json;
    static Tree newTree;
    static Funciones func = new Funciones();
    /**
     * Creates new form AÑADIR_MIEMBRO
     */
    public CONTROL_REGISTROS(Tree newTree, LecturaJSON json) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.newTree=newTree;
        this.json=json;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        REGRESAR = new javax.swing.JButton();
        INSTRUCCIONES = new javax.swing.JButton();
        INPUT_NAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CERRAR = new javax.swing.JButton();
        BUSCAR_NOMBRE = new javax.swing.JButton();
        BUSCAR_APODO = new javax.swing.JButton();
        VER_ARBOL = new javax.swing.JButton();
        ICONO = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE REGISTROS");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROL DE REGISTROS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        REGRESAR.setBackground(new java.awt.Color(0, 0, 0));
        REGRESAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        REGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        REGRESAR.setText("REGRESAR");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });
        getContentPane().add(REGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        INSTRUCCIONES.setBackground(new java.awt.Color(0, 0, 0));
        INSTRUCCIONES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INSTRUCCIONES.setForeground(new java.awt.Color(255, 255, 255));
        INSTRUCCIONES.setText("INSTRUCCIONES");
        INSTRUCCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSTRUCCIONESActionPerformed(evt);
            }
        });
        getContentPane().add(INSTRUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        INPUT_NAME.setBackground(new java.awt.Color(0, 0, 0));
        INPUT_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INPUT_NAME.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(INPUT_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 420, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESA EL NOMBRE O APODO DEL FAMILIAR:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, -1));

        CERRAR.setBackground(new java.awt.Color(255, 0, 0));
        CERRAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CERRAR.setForeground(new java.awt.Color(255, 255, 255));
        CERRAR.setText("X");
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });
        getContentPane().add(CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        BUSCAR_NOMBRE.setBackground(new java.awt.Color(0, 0, 0));
        BUSCAR_NOMBRE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BUSCAR_NOMBRE.setForeground(new java.awt.Color(255, 255, 255));
        BUSCAR_NOMBRE.setText("BUSCAR POR NOMBRE");
        BUSCAR_NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_NOMBREActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        BUSCAR_APODO.setBackground(new java.awt.Color(0, 0, 0));
        BUSCAR_APODO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BUSCAR_APODO.setForeground(new java.awt.Color(255, 255, 255));
        BUSCAR_APODO.setText("BUSCAR POR APODO");
        BUSCAR_APODO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_APODOActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR_APODO, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 180, 180, -1));

        VER_ARBOL.setBackground(new java.awt.Color(0, 0, 0));
        VER_ARBOL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VER_ARBOL.setForeground(new java.awt.Color(255, 255, 255));
        VER_ARBOL.setText("VER ARBOL GENEALÓGICO");
        VER_ARBOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_ARBOLActionPerformed(evt);
            }
        });
        getContentPane().add(VER_ARBOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        ICONO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PERSONA.png"))); // NOI18N
        getContentPane().add(ICONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FONDO.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CERRARActionPerformed

    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/ICONO_TRONO.png"));
        return icono;
    }
    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        MENU M = new MENU(newTree, json);
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_REGRESARActionPerformed

    private void BUSCAR_NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR_NOMBREActionPerformed
        try {
            String nombrePersona = INPUT_NAME.getText();
            if (!nombrePersona.isBlank()) {
                }
            else {
                JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la persona que desea buscar 👤️");
            }
            INPUT_NAME.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado!!!");
        }
    }//GEN-LAST:event_BUSCAR_NOMBREActionPerformed

    private void BUSCAR_APODOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR_APODOActionPerformed
        try {
            String nombrePersona = INPUT_NAME.getText();
            if (!nombrePersona.isBlank()) {
                }
            else {
                JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la persona que desea buscar 👤️");
            }
            INPUT_NAME.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado!!!");
        }
    }//GEN-LAST:event_BUSCAR_APODOActionPerformed

    private void INSTRUCCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSTRUCCIONESActionPerformed
        JOptionPane.showMessageDialog(this, "👤\n️"
                                        +"👤\n️");
    }//GEN-LAST:event_INSTRUCCIONESActionPerformed

    private void VER_ARBOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_ARBOLActionPerformed
        try {
            newTree.setGraph(new MultiGraph("Árbol Genealógico"));
            newTree.mostrarArbol();
            func.appendGraph(newTree, newTree.getpRoot(), null);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado!!!");
       }
    }//GEN-LAST:event_VER_ARBOLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONTROL_REGISTROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONTROL_REGISTROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONTROL_REGISTROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONTROL_REGISTROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONTROL_REGISTROS(newTree,json).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR_APODO;
    private javax.swing.JButton BUSCAR_NOMBRE;
    private javax.swing.JButton CERRAR;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel ICONO;
    private javax.swing.JTextField INPUT_NAME;
    private javax.swing.JButton INSTRUCCIONES;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JButton VER_ARBOL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
