/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VENTANAS;

import EDD.Tree;
import JSON.LecturaJSON;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class MENU extends javax.swing.JFrame {
    static boolean jsoncargado;
    static LecturaJSON json;
    static Tree newTree;
    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.newTree = newTree;
        this.jsoncargado = false;
    } 
    public MENU(Tree newTree, LecturaJSON json) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.newTree = newTree;
        this.json = json;
        this.jsoncargado = true;
    }
    
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/ICONO_TRONO.png"));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CERRAR = new javax.swing.JButton();
        TITULO = new javax.swing.JLabel();
        ARBOL = new javax.swing.JLabel();
        INSTRUCCIONES = new javax.swing.JButton();
        CARGAR_JSON = new javax.swing.JButton();
        CONTROL_REGISTROS = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENÚ PRINCIPAL");
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setName(""); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CERRAR.setBackground(new java.awt.Color(255, 0, 0));
        CERRAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CERRAR.setForeground(new java.awt.Color(255, 255, 255));
        CERRAR.setText("X");
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });
        getContentPane().add(CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        TITULO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("MENÚ PRINCIPAL");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        ARBOL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ARBOL.png"))); // NOI18N
        getContentPane().add(ARBOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        INSTRUCCIONES.setBackground(new java.awt.Color(0, 0, 0));
        INSTRUCCIONES.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INSTRUCCIONES.setForeground(new java.awt.Color(255, 255, 255));
        INSTRUCCIONES.setText("INSTRUCCIONES");
        INSTRUCCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSTRUCCIONESActionPerformed(evt);
            }
        });
        getContentPane().add(INSTRUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        CARGAR_JSON.setBackground(new java.awt.Color(0, 0, 0));
        CARGAR_JSON.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CARGAR_JSON.setForeground(new java.awt.Color(255, 255, 255));
        CARGAR_JSON.setText("CARGAR JSON");
        CARGAR_JSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGAR_JSONActionPerformed(evt);
            }
        });
        getContentPane().add(CARGAR_JSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        CONTROL_REGISTROS.setBackground(new java.awt.Color(0, 0, 0));
        CONTROL_REGISTROS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CONTROL_REGISTROS.setForeground(new java.awt.Color(255, 255, 255));
        CONTROL_REGISTROS.setText("CONTROL DE REGISTROS");
        CONTROL_REGISTROS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTROL_REGISTROSActionPerformed(evt);
            }
        });
        getContentPane().add(CONTROL_REGISTROS, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/FONDO.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRARActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CERRARActionPerformed

    private void CARGAR_JSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGAR_JSONActionPerformed
        CARGAR_JSON CJ = new CARGAR_JSON(newTree, json); 
        this.setVisible(false);
        CJ.setVisible(true);
    }//GEN-LAST:event_CARGAR_JSONActionPerformed

    private void CONTROL_REGISTROSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTROL_REGISTROSActionPerformed
        if(jsoncargado){
            CONTROL_REGISTROS CR = new CONTROL_REGISTROS(newTree, json); 
            this.setVisible(false);
            CR.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Debe cargar primero un archivo JSON");
        }
    }//GEN-LAST:event_CONTROL_REGISTROSActionPerformed

    private void INSTRUCCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSTRUCCIONESActionPerformed
        JOptionPane.showMessageDialog(this, "👤\n️"
                                        +"👤\n️");
    }//GEN-LAST:event_INSTRUCCIONESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ARBOL;
    private javax.swing.JButton CARGAR_JSON;
    private javax.swing.JButton CERRAR;
    private javax.swing.JButton CONTROL_REGISTROS;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton INSTRUCCIONES;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
